baseURL = "https://lsq.github.io"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "lsq 的博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。<br /><br />背景使用了 <a href="https://www.pexels.com/zh-cn/" target="_blank">Pexels</a> 上 <a href="https://www.pexels.com/zh-cn/@minan1398" target="_blank">Min An</a> 拍摄的<a href="https://www.pexels.com/zh-cn/photo/1454794/" target="_blank">图片</a>。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "lsq"

enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 6

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "#fff"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  # defaultDark = true
  # backgroundDark = "#222"
  backgroundImageDark = "/me/background.jpg"
  darkLinkColor = "darkseagreen"
  # darkNav = true
  # dark404 = true

  images = ["me/background.jpg"]

  author = "lsq"
  description = "lsq成长记录～"
  avatar = "/me/pk.jpg"
  headerTitle = "lsq的博客"
#motto = "与其感慨路难行，不如马上出发。"
  motto = "世界经济史是一部基于假象和谎言的连续剧"
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = true

  utterancesRepo = "lsq/lsq.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""

  email = "lsqypj@gmail.com"
#  twitter = "g1eny0ung"
#  facebook = "g1eny0ung"
#  instagram = "g1eny0ung"
  # mastodon = ""
#  linkedin = "g1eny0ung"
  github = "lsq"
#  stackoverflow = "5676489/g1eny0ung"
#  codepen = "g1eny0ung"

  siteStartYear = 2011

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true

  [params.advanced]
    customCSS = ["css/custom.css"]
    customJS = []
